minecraft-server:
  ports:
    - "52174:25565"

  environment:
    EULA: "TRUE"
    TYPE: "FABRIC"
    VERSION: "1.15.2"
    MAX_MEMORY: 1.5G

  image: itzg/minecraft-server:adopt13
  volumes:
          - "/etc/mc-server/data:/data"
  container_name: mc-server

  tty: true
  stdin_open: true
  restart: always
