minecraft-server:
  ports:
    - "52174:25565"

  environment:
    EULA: "TRUE"
    TYPE: "FORGE"
    VERSION: "1.12.2"
    FORGEVERSION: "14.23.5.2838"
    FORGE_INSTALLER_URL: "https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-installer.jar"
    MAX_MEMORY: 3G

  image: itzg/minecraft-server
  volumes:
          - "/etc/mc-server/data:/data"
  container_name: mc-server

  tty: true
  stdin_open: true
  restart: always
